name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  
  # Allows manual execution from the Actions tab
  workflow_dispatch:
  
  # Also runs on every push to the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checks out your repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generates the snake files (both light and dark SVGs, plus a GIF)
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: xam1tovv
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Pushes the generated files only to the "output" branch
      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
